config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/dex'
  get 'pages/breaking_news'
  get 'pages/playbox'
  get 'pages/breaking'
  get 'pages/demo1'
  get 'pages/bluebird'
  root to: 'pages#index'

  resources :articles
  resources :images
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :article_image_associations, -> { order(position: :asc) }, dependent: :destroy
  has_many :images, through: :article_image_associations
  accepts_nested_attributes_for :article_image_associations, allow_destroy: true
  accepts_nested_attributes_for :images
end

app/models/article_image_association.rb
class ArticleImageAssociation < ActiveRecord::Base
  belongs_to :article
  belongs_to :image
  accepts_nested_attributes_for :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :link, ImageUploader

  has_many :article_image_associations, dependent: :destroy
  has_many :articles, through: :article_image_associations

  # def link=(val)
  #   if !val.is_a?(String) && valid?
  #     image_will_change!
  #     super
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.where(state: 'live')
  end

  def show
    @article = Article.find params[:id]
    if(@article.blank? || @article.state != 'live')
      return redirect_to articles_path
    end
  end

  def new
    @article = Article.new
    respond_to do |format|
      format.html { render action: :edit }
      format.json { render json: @article }
    end
  end

  def edit
    @article = Article.find(params[:id])
    respond_to do |format|
      format.html { render :edit }
      format.json { render json: @article }
    end
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to edit_article_path @article
    else
      flash[:warning] = "Error creating article."
      render action: :edit
    end
  end

  def update
    @article = Article.find params[:id]
    slug_adds = params[:add_slug].collect { |slug| Image.where(slug: slug) } if params[:add_slug].present?
    if @article.update article_params
      @article.images << slug_adds if slug_adds.present?
      redirect_to edit_article_path @article
    else
      flash[:warning] = "Error updating article."
      render action: :edit
    end
  end

  def destroy
    @article = Article.find params[:id]
    if @article.destroy
      redirect_to articles_path
    else
      flash[:warning] = "Could not destory article"
      render action: :edit
    end
  end

  def article_params
    params.require(:article).permit(:slug, :headline, :subheadline, :contributors, :date, :body, :state,
      article_image_associations_attributes: [
        :id,
        :position,
        :_destroy,
        image_attributes: [
          :link,
          :slug
        ]
      ],
      images_attributes: [:id, :link, :slug] )
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
    render action: :edit
  end

  def edit
    @image = Image.find params[:id]
  end

  def create
    @image = Image.new image_params
    if @image.save
      redirect_to edit_image_path @image
    else
      flash[:warning] = "Could not create image"
      render action: :edit
    end
  end

  def update
    @image = Image.find params[:id]
    if @image.update image_params
      redirect_to edit_image_path @image
    else
      flash[:warning] = "Error updating image."
      render action: :edit
    end
  end

  def destroy
    @image = Image.find params[:id]
    if(@image.destroy)
      redirect_to images_path
    else
      flash[:warning] = "Could not delete image."
      render action: :edit
    end
  end

  def image_params
    params.require(:image).permit(:slug, :link, :caption, :copyright, :owner)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include ApplicationHelper

  def index
  end

  def breaking
  end

  def playbox
  end

  def dex
  end

  def demo1
    @disable_foundation = true
  end

  def bluebird
  end

  def breaking_news
    # headers['Last-Modified'] = Time.now.httpdate
    # render json: ApplicationHelper.getContentAPIData(params[:params])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def parse_body(body, images)
    ret_body = body.gsub(/\r/, '').gsub(/\n/, '<br />')
    index = 0
    ret_body.gsub('[image]') { |match| images[index=index+1] ? image_tag(images[index].try(:link), width: '230') : '' }.html_safe
  end

  def state_options
    [["Working", 'working'], ["Live", 'live']]
  end
end

app/views/articles/_main_image.html.erb
<div>
  <%= image_tag image.link, width: '400' %>
  <div><%= image.caption %></div>
  <div>Copyright: <%= image.owner %></div>
</div>

app/views/articles/edit.html.erb
<%= react_component 'ArticleEdit', @article.to_json(root: false, include: [article_image_associations: { root: false, include: [:image] }]) %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.slug, article_path(article) %>
      <%= link_to "E", edit_article_path(article) %>
      <%= link_to "X", article_path(article), method: :delete, data: { confirm: "Sure?" } %>
    </li>
  <% end %>
</ul>

app/views/articles/show.html.erb
<%= react_component 'ArticleShow', @article.to_json(root: false, include: [images: { root: false }]) %>

app/views/images/edit.html.erb
<h1>Image</h1>
<%= form_for @image do |f| %>
  <%= f.hidden_field :id %>

  <% if f.object.link %>
    <%= image_tag f.object.link, width: '400' %>
    <br />
    <%= f.label :link, "Upload New Image" %>
    <%= f.file_field :link %>
  <% else %>
    <%= f.label :link, "Upload Image" %>
    <%= f.file_field :link %>
  <% end %>
  <br />

  <%= f.label :slug %>
  <%= f.text_field :slug %>
  <br />

  <%= f.label :caption %>
  <%= f.text_area :caption %>
  <br />

  <%= f.label :copyright %>
  <%= f.text_area :copyright %>
  <br />

  <%= f.label :owner %>
  <%= f.text_field :owner %>
  <br />

  <%= f.submit f.object.new_record? ? "Create" : "Update" %>
<% end %>

app/views/images/index.html.erb
<h1>Images</h1>
<ul>
  <% @images.each do |image| %>
    <li>
      <%= image_tag image.link, width: "64" %>
      <%= image.slug %>
      <%= link_to 'E', edit_image_path(image) %>
      <%= link_to "X", image_path(image), method: :delete, data: { confirm: "Sure?" } %>
    </li>
  <% end %>
</ul>

app/views/images/show.html.erb
<h1>Image#show</h1>
<p>Find me in app/views/image/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dex Demos</title>
  <%= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true ) unless @disable_foundation %>
  <%= csrf_meta_tags %>
</head>
<body <%= yield :seed_attributes %>>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/bluebird.html.erb
<% content_for :seed_attributes do %>
data-bluebird-store="an initial message"
<% end %>
<h1>BlueBird</h1>
<%= react_component "BlueBirdStats", {} %>
<%= react_component "BlueBirdContainer", {} %>
<%= react_component "BlueBirdContainer", { reverse: true } %>

app/views/pages/demo1.html.erb
<h1>Demo 1</h1>
<%= react_component "InteractiveExample", {} %>

<%#
  react_component "ComponentName", {props}
  calls
  React.renderComponent(
    React.createElement("InteractiveExample", props />)
  );
%>

<h1>Demo 2</h1>
<%= react_component "Demo2", {} %>

app/views/pages/dex.html.erb
<h1>DEX - Chicago Breaking News</h1>

<%
  # NEVER PUT LOGIC LIKE THIS IN A VIEW
  random_words = [
    ["apple", "bannana", "watermelon", "oranges", "ice cream"],
    [],
    ["alpha", "beta", "gamma", "iota"],
    ["hot dog", "mustard", "guava"],
    ["chocolate", "ice cream", "cookies", "brownies"],
    ["dog", "cat", "iguana", "leopard", "bear"]
  ]
%>

<% random_words.each_with_index do |random_word_group, index| %>
  
  <h2>Container <%= index + 1 %></h2>
  <%= react_component 'Container', { items: random_word_group } %>

<% end %>

app/views/pages/index.html.erb
<h1>BlueBird - Index</h1>
<%= react_component 'BlueBirdContainer' %>

app/views/pages/playbox.html.erb
<h1>Play Box</h1>
<%= react_component "PlayBox", {} %>